const tangibleSingularProperties = [
    'ass',
    'belly button',
    'booty',
    'bottom lip',
    'brain',
    'bum',
    'butt',
    'chin',
    'demeanour',
    'face',
    'fashion sense',
    'forehead',
    'heart',
    'index finger',
    'keister',
    'laugh',
    'left foot',
    'left hand',
    'little toe',
    'mind',
    'mouth',
    'neck',
    'outlook on life',
    'posterior',
    'radiance',
    'right foot',
    'right hand',
    'smile',
    'soul',
    'thumb',
    'tongue',
    'tush',
    'tushie',
    'vibe',
    'voice',
    'way of thinking',
    'work ethic',
    'idea', 'imagination', 'suggestion', 'mind', 'spirit', 'vision', 'wisdom', 'advice', 'something', 'stuff', 'notion', 'soul', 'philosophy', 'message', 'knowledge', 'opinion', 'feedback', 'perspective', 'chance', 'impression', 'view', 'way', 'passion', 'conversation', 'belief', 'dream', 'sense', 'theory', 'discussion', 'excitement', 'fun', 'curiosity', 'kind', 'information', 'personality', 'conjecture', 'theme', 'sort', 'anything', 'desire', 'chatter', 'mood', 'opportunity', 'faith', 'zest', 'insight', 'thing', 'emotion', 'gossip', 'story', 'discourse', 'thread', 'enthusiasm', 'laugh', 'possibility', 'inspiration', 'attitude', 'everything', 'hypothesis', 'purpose', 'hope', 'pleasure', 'poetry', 'talk', 'dreamer', 'impulse', 'instinct', 'Talk', 'laughter', 'table', 'feeling', 'topic', 'interpretation', 'eagerness', 'joy', 'praise', 'synopsis', 'fantasy', 'content', 'exuberance', 'rhetoric', 'love', 'aim', 'wish', 'mentality', 'future', 'logic', 'impetus', 'natures', 'muse', 'humanity', 'criticism', 'religion', 'rumor', 'motivation', 'analogy', 'rationale', 'answer', 'commentary', 'tweet', 'potpourri', 'thinking', 'supposition', 'intention', 'perception', 'chuckle', 'visions', 'ambition', 'essay', 'weirdness', 'hyperbole', 'admonition', 'inclination', 'narrative', 'listener', 'debate', 'brighten', 'lyric', 'fervor', 'moments', 'worlds', 'dreamers', 'thought', 'share', 'minds', 'souls', 'friends', 'characters', 'talking', 'writing', 'try', 'things', 'might'
];

const tangibleMultipleProperties = [
    'ankles',
    'buttocks',
    'calves',
    'clothes',
    'ears',
    'elbows',
    'eyebrows',
    'eyelashes',
    'eyes',
    'facial hair',
    'feet',
    'fingernails',
    'fingers',
    'forearms',
    'hair',
    'hands',
    'hips',
    'ideas',
    'knees',
    'legs',
    'muscles',
    'skills',
    'skin',
    'strengths',
    'teeth',
    'thighs',
    'thighs',
    'thoughts',
    'toenails',
    'toes',
    'wrists',
    'thoughts', 'ideas', 'suggestions', 'visions', 'experiences', 'notions', 'theories', 'things', 'dreams', 'memories', 'minds', 'feelings', 'stories', 'impressions', 'reflections', 'observations', 'views', 'recollections', 'words', 'emotions', 'ways', 'questions', 'possibilities', 'tips', 'tales', 'hints', 'strategies', 'senses', 'aspirations', 'guesses', 'opinions', 'facts', 'messages', 'wishes', 'myths', 'habits', 'imaginations', 'comments', 'secrets', 'speculations', 'details', 'conjectures', 'hypotheses', 'bits', 'aspects', 'qualities', 'sketches', 'voices', 'conclusions', 'conceptions', 'responses', 'inclinations', 'touches', 'traits', 'souls', 'imaginings', 'sentiments', 'daydreams', 'preferences', 'energies', 'glimpses', 'chances', 'realities', 'perceptions', 'fantasies', 'happenings', 'hopes', 'noises', 'friends', 'particulars', 'moods', 'impulses', 'influences', 'reminiscences', 'reasons', 'doubts', 'Things', 'brains', 'pursuits', 'explorations', 'greetings', 'illusions', 'beliefs', 'criticisms', 'options', 'moments', 'poems', 'traditions', 'images', 'folks', 'clues', 'explanations', 'guys', 'prejudices', 'worlds', 'laughs', 'reactions', 'considerations', 'issues', 'plans', 'intentions', 'threads', 'writings', 'approaches', 'narratives', 'characters', 'projections', 'concerns', 'situations', 'descriptions', 'paths', 'joys', 'interests', 'remarks', 'phantoms', 'intimations', 'scenarios', 'expectations', 'meanings', 'selections', 'ambitions', 'attitudes', 'hobbies', 'tendencies', 'rumors', 'phrases', 'discourses', 'horizons', 'articles', 'whisperings', 'intellects', 'instincts', 'positives', 'expressions', 'lessons', 'smiles', 'scraps', 'excuses', 'compliments', 'morsels', 'reviews', 'absurdities', 'surprises', 'tidings', 'allusions', 'curiosities', 'destinies', 'invitations', 'findings', 'videos'
];

const adjectives = [
    'adorable',
    'alluring',
    'amazeballs',
    'amazing',
    'angelic',
    'astonishing',
    'astounding',
    'attractive',
    'awe-inspiring',
    'awesome',
    'beautiful',
    'beguiling',
    'bewildering',
    'bewitching',
    'breathtaking',
    'charming',
    'comely',
    'crazy',
    'cute',
    'dazzling',
    'delightful',
    'divine',
    'dreamy',
    'exquisite',
    'extraordinary',
    'fantastic',
    'glamorous',
    'gorgeous',
    'great',
    'handsome',
    'heavenly',
    'hot',
    'impressive',
    'incredible',
    'insane',
    'irresistible',
    'lovely',
    'magnificent',
    'majestic',
    'marvellous',
    'marvelous',
    'mind-blowing',
    'mind-boggling',
    'nice',
    'perfect',
    'phenomenal',
    'pleasing',
    'preposterous',
    'pretty',
    'radiant',
    'ravishing',
    'remarkable',
    'sensational',
    'smashing',
    'spectacular',
    'splendid',
    'stunning',
    'stupefying',
    'stupendous',
    'sublime',
    'superb',
    'supercalifragilisticexpialidocious',
    'sweet',
    'tasty',
    'terrific',
    'tremendous',
    'unbelievable',
    'useful',
    'wonderful',
    'wowzers',
    'awesome', 'fantastic', 'incredible', 'great', 'nice', 'unbelievable', 'fabulous', 'terrific', 'wonderful', 'good', 'weird', 'impressive', 'marvelous', 'beautiful', 'awful', 'excellent', 'amazing', 'lovely', 'crazy', 'horrible', 'gorgeous', 'perfect', 'terrible', 'interesting', 'exciting', 'indescribable', 'tremendous', 'delicious', 'easy', 'glad', 'insane', 'cool', 'refreshing', 'okay', 'enjoyable', 'stupendous', 'happy', 'strange', 'huge', 'mad', 'brilliant', 'remarkable', 'funny', 'monstrous', 'stupid', 'odd', 'solid', 'big', 'exceptional', 'sweet', 'splendid', 'tasty', 'hideous', 'cute', 'spectacular', 'enormous', 'gigantic', 'unreal', 'important', 'immense', 'scary', 'bad', 'unique', 'tough', 'memorable', 'stellar', 'ultimate', 'infinite', 'pleasant', 'magical', 'decent', 'whole', 'uncanny', 'luscious', 'sad', 'hellish', 'ideal', 'glorious', 'intriguing', 'different', 'real', 'capable', 'proud', 'overwhelming', 'hard', 'absolute', 'shocking', 'astonishing', 'awkward', 'prodigious', 'sorry', 'ecstatic', 'obvious', 'unusual', 'primal', 'true', 'honest', 'elegant', 'strong', 'curious', 'endless', 'classic', 'intense', 'delightful', 'surprising', 'titanic', 'classy', 'crisp', 'dazzling', 'mellow', 'ready', 'wise', 'sure', 'mighty', 'able', 'sheer', 'fascinating', 'unfortunate', 'unforgettable', 'superb', 'impossible', 'appalling', 'powerful', 'comfortable', 'super', 'special', 'ugly', 'snappy', 'quick', 'satisfying', 'unimaginable', 'extraordinary', 'meaty', 'stylish', 'funky', 'speechless', 'dominant', 'lush', 'ethereal', 'fearsome', 'limitless', 'frightful', 'silky', 'formidable', 'entire', 'nauseous', 'sexy', 'alien', 'bizarre', 'equal'
];

const adverbs = [
    'absolutely',
    'awfully',
    'bloody',
    'completely',
    'decidedly',
    'deeply',
    'devilishly',
    'distinctly',
    'entirely',
    'especially',
    'ever so',
    'exceedingly',
    'exceptionally',
    'extraordinarily',
    'extremely',
    'fairly',
    'frightfully',
    'highly',
    'hugely',
    'immensely',
    'incredibly',
    'inordinately',
    'insanely',
    'intensely',
    'mightily',
    'oh-so',
    'outstandingly',
    'particularly',
    'perfectly',
    'positively',
    'practically',
    'pretty',
    'purely',
    'quite',
    'radiantly',
    'rather',
    'really',
    'remarkably',
    'seriously',
    'simply',
    'so',
    'somewhat',
    'sort of',
    'supremely',
    'terribly',
    'thoroughly',
    'totally',
    'totes',
    'tremendously',
    'truly',
    'unusually',
    'utterly',
    'very',
    'virtually',
    'virtually', 'absolutely', 'utterly', 'really', 'totally', 'obviously', 'certainly', 'completely', 'truly', 'always', 'very', 'indeed', 'extremely', 'frankly', 'wholly', 'not', 'quite', 'almost', 'so', 'equally', 'incredibly', 'just', 'clearly', 'virtually', 'definitely', 'entirely', 'never', 'here', 'unbelievably', 'everywhere', 'especially', 'still', 'now', 'hardly', 'perfectly', 'pretty', 'plainly', 'therefore', 'evidently', 'particularly', 'doubly', 'probably', 'thoroughly', 'fantastically', 'profoundly', 'actually', 'exactly', 'terribly', 'hideously', 'seemingly', 'simply', 'practically', 'deeply', 'else', 'whatsoever', 'highly', 'tremendously', 'otherwise', 'undoubtedly', 'enormously', 'again', 'wonderfully', 'basically', 'ever', 'already', 'yet', 'fairly', 'anymore', 'horribly', 'even', 'fully', 'damned', 'singularly', 'infinitely', 'somehow', 'exceedingly', 'personally', 'however', 'essentially', 'anyhow', 'extraordinarily', 'surely', 'forever', 'hugely', 'only', 'anywhere', 'literally', 'nearly', 'sadly', 'immediately', 'too', 'exceptionally', 'overly', 'sometimes', 'hopelessly', 'firmly', 'anyway', 'suddenly', 'deliciously', 'positively', 'once', 'purely', 'strangely', 'fortunately', 'constantly', 'scarcely', 'afterward', 'mildly', 'unmistakably', 'amazingly', 'faintly', 'insanely', 'likewise', 'merely', 'somewhat', 'madly', 'shockingly', 'frightfully', 'Well', 'vaguely', 'apparently', 'precisely', 'maybe', 'necessarily', 'uniformly', 'greatly', 'strongly', 'forward', 'reasonably', 'grotesquely', 'badly', 'absurdly', 'nowhere', 'strictly', 'wildly', 'weirdly', 'awfully', 'technically', 'desperately', 'altogether', 'naturally', 'peculiarly', 'rightly', 'phenomenally', 'immensely', 'nevertheless', 'undeniably', 'vigorously', 'enough', 'repeatedly', 'patently'
];

export {
    tangibleMultipleProperties,
    tangibleSingularProperties,
    adjectives,
    adverbs
};
